services:
  dailry-blue:
    container_name: dailry-blue
    image: ${DAILRY_IMAGE}
    ports:
      - 8081:8080
    env_file:
      - .env

  dailry-green:
    container_name: dailry-green
    image: ${DAILRY_IMAGE}
    ports:
      - 8082:8080
    env_file:
      - .env
